title: "The Ray Lab"
author: "Debashis Ray"
description:  "	&#169; 2021, Debashis Ray"
# description: "Made with <b style=\"color: #f45;\">&lt;3</b>" #Displays Made with <3 at the bottom
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
# google_analytics: G-D62XCTV35T

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "alumni.md", title: "Alumni"} 
  - {file: "news.md", title: "News"}
 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:dray@chem.iitkgp.ac.in"}
#   - {title: Github, icon: github, url: "https://github.com/debanik09"}
#   - {title: Facebook, icon: facebook, url: "https://facebook.com/debanik.ray"}
#   - {title: Twitter, icon: twitter, url: "https://twitter.com/bakedrainy"}
#   - {title: Cinéaste, icon: film, url: "https://letterboxd.com/wrik/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
